 version: '2'
 services:
   db:
     image: imiell/sqlite
   web:
     build: .
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - /webapp:/code
     ports:
       - "8000:8888"
     depends_on:
       - db