# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0003_auto_20160923_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ManyToManyField(to='dtree.Question'),
        ),
    ]
