# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0005_remove_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='dataSet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtree.DataSet'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtree.Question'),
        ),
    ]
