# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0006_auto_20160923_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='dataSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtree.DataSet'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtree.Question'),
        ),
    ]
