# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0007_auto_20160926_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
