# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0009_auto_20160926_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='n',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='y',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
