# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0011_question_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='progress',
            field=models.BooleanField(default=True),
        ),
    ]
