# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0012_auto_20160927_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='progress',
            new_name='isquestion',
        ),
    ]
